In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('맥주이름.csv', encoding='utf-8', index_col=0)

In [3]:
data

                                           맥주
0                      Kloud Original Gravity
1                      Kloud Fitz Super Clear
2                             Asahi Super Dry
3                                    Tsingtao
4                                    Heineken
..                                        ...
60      Volfas Engelman Grünberger Hefeweizen
61  Berliner Kindl Jubiläums Pilsener Premium
62                                   Red Rock
63                  Erdinger Weissbier Dunkel
64                   Warsteiner Premium Verum

[65 rows x 1 columns]

In [4]:
tmp = data['맥주'].tolist()

In [5]:
tmp

['Kloud Original Gravity',
 'Kloud Fitz Super Clear',
 'Asahi Super Dry',
 'Tsingtao',
 'Heineken',
 'Kirin Ichiban',
 'Sapporo Premium Beer',
 'Stella Artois',
 'Guinness Draught',
 'Kronenbourg 1664 Blanc',
 'Pilsner Urquell',
 'San Miguel',
 'OB Premier Pilsner',
 'Cass Fresh',
 'Hite D (Dry Finish)',
 'Hite Prime Max',
 'Hite Extra Cold',
 'Victoria Bitter',
 'Bintang Pilsener',
 'Krombacher Weizen',
 'Miller Genuine Draft (MGD)',
 'Tiger Radler Lemon',
 "Suntory The Premium Malt's",
 'Reeper B. Exotisches IPA',
 'Tiger Beer',
 'Tsingtao Wheat Beer',
 'Erdinger Weissbier',
 'Carlsberg Pilsner',
 'Budweiser',
 'Hoegaarden',
 'Sapporo Yebisu',
 'Paulaner Hefe-Weissbier',
 'Desperados',
 'Peroni Nastro Azzurro',
 'Edelweiss Weissbier Snowfresh',
 'Heineken Dark Lager',
 'Kozel Černý (Dark) 10°',
 'Guinness Original 4.2%',
 'Jeju Wit Ale',
 'Stephans Bräu Premium Pilsener',
 'Stephans Bräu Premium Lager',
 'Stephans Bräu Hefe-Weizen Naturtrüb',
 'Eichbaum Apostel Bräu',
 'Egger Märzenbier',
 'Holsten Premium Bier',
 'Franziskaner Hefe-Weissbier',
 'Egger Grapefruit Radler',
 'Bavaria Pilsener',
 'Bavaria 8.6 (Original)',
 'Lapin Kulta IV A',
 'Grolsch Premium Lager',
 'Gambrinus Originál 10° (Desítka)',
 'Castlemaine XXXX Gold Lager',
 'Leffe Brune',
 'Löwenbräu Original (4.2%)',
 'Asahi Super Dry Black',
 'Harbin Beer',
 "Beck's",
 'Hoegaarden Rosée',
 'Schöfferhofer Grapefruit',
 'Volfas Engelman Grünberger Hefeweizen',
 'Berliner Kindl Jubiläums Pilsener Premium',
 'Red Rock',
 'Erdinger Weissbier Dunkel',
 'Warsteiner Premium Verum']

In [43]:
pd.set_option('display.max_rows', 100)

In [45]:
data = pd.read_csv('맥주_10.csv', encoding='utf-8', index_col=0)
data

                        아이디                        맥주   평점
2       snoworsummer(8,581)    Kloud Original Gravity  3.0
4      GuideDogSaint(2,549)    Kloud Original Gravity  2.2
5            deanso(13,380)    Kloud Original Gravity  2.3
7            DrNosha(5,865)    Kloud Original Gravity  2.3
8             mkel07(8,991)    Kloud Original Gravity  2.4
...                     ...                       ...  ...
2446     beerman991979(136)  Warsteiner Premium Verum  3.2
2448          Aubrey(3,516)  Warsteiner Premium Verum  2.9
2449            Sammys(427)  Warsteiner Premium Verum  2.9
2450            Bov(14,984)  Warsteiner Premium Verum  2.2
2451  PhillyBeer2112(3,215)  Warsteiner Premium Verum  3.8

[45068 rows x 3 columns]

In [46]:
data = data[['아이디','맥주','평점']]
data.head(3)

                    아이디                      맥주   평점
2   snoworsummer(8,581)  Kloud Original Gravity  3.0
4  GuideDogSaint(2,549)  Kloud Original Gravity  2.2
5        deanso(13,380)  Kloud Original Gravity  2.3

In [47]:
beer_name = data.맥주.unique()

In [48]:
beer_name = pd.DataFrame(data=beer_name, columns=['맥주이름'])

In [49]:
beer_name.sort_values(by='맥주이름')

                                                 맥주이름
2                                     Asahi Super Dry
55                              Asahi Super Dry Black
48                             Bavaria 8.6 (Original)
47                    Bavaria Pilsener / Premium Beer
57                                             Beck's
61          Berliner Kindl Jubiläums Pilsener Premium
18                                   Bintang Pilsener
28                                          Budweiser
27                                  Carlsberg Pilsner
13                                         Cass Fresh
52                        Castlemaine XXXX Gold Lager
32                                         Desperados
34                      Edelweiss Weissbier Snowfresh
46                            Egger Grapefruit Radler
43                                   Egger Märzenbier
42                              Eichbaum Apostel Bräu
26                                 Erdinger Weissbier
63                          Erdinger Weissbier Dunkel
45  Franziskaner Hefe-Weissbier / Weissbier Naturtrub
51                   Gambrinus Originál 10° (Desítka)
50                              Grolsch Premium Lager
8                                    Guinness Draught
37                Guinness Original 4.2% (Ireland/UK)
56                                        Harbin Beer
4                                            Heineken
35                                Heineken Dark Lager
14                                Hite D (Dry Finish)
16                                    Hite Extra Cold
15                                     Hite Prime Max
29                                         Hoegaarden
58                                   Hoegaarden Rosée
44                               Holsten Premium Bier
38                                       Jeju Wit Ale
5                                       Kirin Ichiban
1                              Kloud Fitz Super Clear
0                              Kloud Original Gravity
36                             Kozel Černý (Dark) 10°
19                                  Krombacher Weizen
9                              Kronenbourg 1664 Blanc
49                                   Lapin Kulta IV A
53                        Leffe Brune / Bruin / Brown
54                          Löwenbräu Original (4.2%)
20                         Miller Genuine Draft (MGD)
12                                 OB Premier Pilsner
31                            Paulaner Hefe-Weissbier
33                              Peroni Nastro Azzurro
10                                    Pilsner Urquell
62                                           Red Rock
23                           Reeper B. Exotisches IPA
11                                         San Miguel
6                   Sapporo Premium Beer / Draft Beer
30                                     Sapporo Yebisu
59                           Schöfferhofer Grapefruit
7                                       Stella Artois
41                Stephans Bräu Hefe-Weizen Naturtrüb
40                        Stephans Bräu Premium Lager
39                     Stephans Bräu Premium Pilsener
22                         Suntory The Premium Malt's
24                                         Tiger Beer
21                                 Tiger Radler Lemon
3                                            Tsingtao
25                                Tsingtao Wheat Beer
17                                    Victoria Bitter
60              Volfas Engelman Grünberger Hefeweizen
64                           Warsteiner Premium Verum

In [54]:
beer_name.to_csv('맥주이름.csv', encoding='utf-8')

In [51]:
beer_name.sort_values(by=['맥주이름'], inplace=True)

In [52]:
tuple([beer_name['맥주이름'].iloc[0]])

('Asahi Super Dry',)

In [53]:
tmp = beer_name['맥주이름'].apply(lambda x: tuple([x,x]))
tmp.to_list()

[('Asahi Super Dry', 'Asahi Super Dry'),
 ('Asahi Super Dry Black', 'Asahi Super Dry Black'),
 ('Bavaria 8.6 (Original)', 'Bavaria 8.6 (Original)'),
 ('Bavaria Pilsener / Premium Beer', 'Bavaria Pilsener / Premium Beer'),
 ("Beck's", "Beck's"),
 ('Berliner Kindl Jubiläums Pilsener Premium',
  'Berliner Kindl Jubiläums Pilsener Premium'),
 ('Bintang Pilsener', 'Bintang Pilsener'),
 ('Budweiser', 'Budweiser'),
 ('Carlsberg Pilsner', 'Carlsberg Pilsner'),
 ('Cass Fresh', 'Cass Fresh'),
 ('Castlemaine XXXX Gold Lager', 'Castlemaine XXXX Gold Lager'),
 ('Desperados', 'Desperados'),
 ('Edelweiss Weissbier Snowfresh', 'Edelweiss Weissbier Snowfresh'),
 ('Egger Grapefruit Radler', 'Egger Grapefruit Radler'),
 ('Egger Märzenbier', 'Egger Märzenbier'),
 ('Eichbaum Apostel Bräu', 'Eichbaum Apostel Bräu'),
 ('Erdinger Weissbier', 'Erdinger Weissbier'),
 ('Erdinger Weissbier Dunkel', 'Erdinger Weissbier Dunkel'),
 ('Franziskaner Hefe-Weissbier / Weissbier Naturtrub',
  'Franziskaner Hefe-Weissbier / Weissbier Naturtrub'),
 ('Gambrinus Originál 10° (Desítka)', 'Gambrinus Originál 10° (Desítka)'),
 ('Grolsch Premium Lager', 'Grolsch Premium Lager'),
 ('Guinness Draught', 'Guinness Draught'),
 ('Guinness Original 4.2% (Ireland/UK)',
  'Guinness Original 4.2% (Ireland/UK)'),
 ('Harbin Beer', 'Harbin Beer'),
 ('Heineken', 'Heineken'),
 ('Heineken Dark Lager', 'Heineken Dark Lager'),
 ('Hite D (Dry Finish)', 'Hite D (Dry Finish)'),
 ('Hite Extra Cold', 'Hite Extra Cold'),
 ('Hite Prime Max', 'Hite Prime Max'),
 ('Hoegaarden', 'Hoegaarden'),
 ('Hoegaarden Rosée', 'Hoegaarden Rosée'),
 ('Holsten Premium Bier', 'Holsten Premium Bier'),
 ('Jeju Wit Ale', 'Jeju Wit Ale'),
 ('Kirin Ichiban', 'Kirin Ichiban'),
 ('Kloud Fitz Super Clear', 'Kloud Fitz Super Clear'),
 ('Kloud Original Gravity', 'Kloud Original Gravity'),
 ('Kozel Černý (Dark) 10°', 'Kozel Černý (Dark) 10°'),
 ('Krombacher Weizen', 'Krombacher Weizen'),
 ('Kronenbourg 1664 Blanc', 'Kronenbourg 1664 Blanc'),
 ('Lapin Kulta IV A', 'Lapin Kulta IV A'),
 ('Leffe Brune / Bruin / Brown', 'Leffe Brune / Bruin / Brown'),
 ('Löwenbräu Original (4.2%)', 'Löwenbräu Original (4.2%)'),
 ('Miller Genuine Draft (MGD)', 'Miller Genuine Draft (MGD)'),
 ('OB Premier Pilsner', 'OB Premier Pilsner'),
 ('Paulaner Hefe-Weissbier', 'Paulaner Hefe-Weissbier'),
 ('Peroni Nastro Azzurro', 'Peroni Nastro Azzurro'),
 ('Pilsner Urquell', 'Pilsner Urquell'),
 ('Red Rock', 'Red Rock'),
 ('Reeper B. Exotisches IPA', 'Reeper B. Exotisches IPA'),
 ('San Miguel', 'San Miguel'),
 ('Sapporo Premium Beer / Draft Beer', 'Sapporo Premium Beer / Draft Beer'),
 ('Sapporo Yebisu', 'Sapporo Yebisu'),
 ('Schöfferhofer Grapefruit', 'Schöfferhofer Grapefruit'),
 ('Stella Artois', 'Stella Artois'),
 ('Stephans Bräu Hefe-Weizen Naturtrüb',
  'Stephans Bräu Hefe-Weizen Naturtrüb'),
 ('Stephans Bräu Premium Lager', 'Stephans Bräu Premium Lager'),
 ('Stephans Bräu Premium Pilsener', 'Stephans Bräu Premium Pilsener'),
 ("Suntory The Premium Malt's", "Suntory The Premium Malt's"),
 ('Tiger Beer', 'Tiger Beer'),
 ('Tiger Radler Lemon', 'Tiger Radler Lemon'),
 ('Tsingtao', 'Tsingtao'),
 ('Tsingtao Wheat Beer', 'Tsingtao Wheat Beer'),
 ('Victoria Bitter', 'Victoria Bitter'),
 ('Volfas Engelman Grünberger Hefeweizen',
  'Volfas Engelman Grünberger Hefeweizen'),
 ('Warsteiner Premium Verum', 'Warsteiner Premium Verum')]

In [23]:
sample = data[:200]
sample

                     아이디                      맥주   평점
0           patjenner(3)  Kloud Original Gravity  4.0
1        pictoman(1,959)  Kloud Original Gravity  2.0
2    snoworsummer(8,581)  Kloud Original Gravity  3.0
3           mickmac(726)  Kloud Original Gravity  2.9
4   GuideDogSaint(2,549)  Kloud Original Gravity  2.2
..                   ...                     ...  ...
86       badpuppy69(736)         Asahi Super Dry  1.5
87                kmt(2)         Asahi Super Dry  3.1
88    EerieDrinks(1,074)         Asahi Super Dry  3.0
89     DraftMonger117(3)         Asahi Super Dry  3.9
90        ZacM612(1,247)         Asahi Super Dry  2.7

[200 rows x 3 columns]

In [24]:
sample.to_csv('샘플.csv', encoding='utf-8')

In [11]:
len(data)

76287

In [8]:
def data_preprocessing():
    data = pd.read_excel('맥주.xlsx')
    id = data['아이디'].iloc[0]
    beer = data['맥주'].iloc[0]
    rating = data['평점'].iloc[0]

    return id, beer, rating

In [9]:
data_preprocessing()

('patjenner(3)', 'Kloud Original Gravity', 4.0)

In [12]:
data['아이디'].value_counts() > 5

TBone(23,237)           True
fonefan(65,420)         True
Oakes(25,346)           True
GoufCustom(2,895)       True
faroeviking(13,765)     True
                       ...
IPA(17)                False
yokeyeow(1)            False
pblpeeerez(20)         False
manwithnoname(1)       False
BeerO_Clock(11)        False
Name: 아이디, Length: 14978, dtype: bool

In [9]:
data.아이디.value_counts()

TBone(23,237)          55
fonefan(65,420)        49
Oakes(25,346)          48
GoufCustom(2,895)      47
faroeviking(13,765)    47
                       ..
IPA(17)                 1
yokeyeow(1)             1
pblpeeerez(20)          1
manwithnoname(1)        1
BeerO_Clock(11)         1
Name: 아이디, Length: 14978, dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 76287 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   아이디     76287 non-null  object
 1   맥주      76287 non-null  object
 2   평점      76287 non-null  float64
dtypes: float64(1), object(2)
memory usage: 2.3+ MB

In [ ]:
data.to_csv()

In [5]:
data = pd.read_csv('맥주이름.csv', encoding='utf-8', index_col=0)

In [6]:
data['맥주이름'].to_list()

['Asahi Super Dry',
 'Asahi Super Dry Black',
 'Bavaria 8.6 (Original)',
 'Bavaria Pilsener / Premium Beer',
 "Beck's",
 'Berliner Kindl Jubiläums Pilsener Premium',
 'Bintang Pilsener',
 'Budweiser',
 'Carlsberg Pilsner',
 'Cass Fresh',
 'Castlemaine XXXX Gold Lager',
 'Desperados',
 'Edelweiss Weissbier Snowfresh',
 'Egger Grapefruit Radler',
 'Egger Märzenbier',
 'Eichbaum Apostel Bräu',
 'Erdinger Weissbier',
 'Erdinger Weissbier Dunkel',
 'Franziskaner Hefe-Weissbier / Weissbier Naturtrub',
 'Gambrinus Originál 10° (Desítka)',
 'Grolsch Premium Lager',
 'Guinness Draught',
 'Guinness Original 4.2% (Ireland/UK)',
 'Harbin Beer',
 'Heineken',
 'Heineken Dark Lager',
 'Hite D (Dry Finish)',
 'Hite Extra Cold',
 'Hite Prime Max',
 'Hoegaarden',
 'Hoegaarden Rosée',
 'Holsten Premium Bier',
 'Jeju Wit Ale',
 'Kirin Ichiban',
 'Kloud Fitz Super Clear',
 'Kloud Original Gravity',
 'Kozel Černý (Dark) 10°',
 'Krombacher Weizen',
 'Kronenbourg 1664 Blanc',
 'Lapin Kulta IV A',
 'Leffe Brune / Bruin / Brown',
 'Löwenbräu Original (4.2%)',
 'Miller Genuine Draft (MGD)',
 'OB Premier Pilsner',
 'Paulaner Hefe-Weissbier',
 'Peroni Nastro Azzurro',
 'Pilsner Urquell',
 'Red Rock',
 'Reeper B. Exotisches IPA',
 'San Miguel',
 'Sapporo Premium Beer / Draft Beer',
 'Sapporo Yebisu',
 'Schöfferhofer Grapefruit',
 'Stella Artois',
 'Stephans Bräu Hefe-Weizen Naturtrüb',
 'Stephans Bräu Premium Lager',
 'Stephans Bräu Premium Pilsener',
 "Suntory The Premium Malt's",
 'Tiger Beer',
 'Tiger Radler Lemon',
 'Tsingtao',
 'Tsingtao Wheat Beer',
 'Victoria Bitter',
 'Volfas Engelman Grünberger Hefeweizen',
 'Warsteiner Premium Verum']